apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: sentinel
data:
  MONITOR_MOCK_SERVICES_URL: "http://mock-services:8001"
  MONITOR_CHECK_INTERVAL_SECONDS: "30"
  MONITOR_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
