apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinel

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres.yaml
  - zookeeper.yaml
  - kafka.yaml
  - mock-services.yaml
  - backend.yaml
  - backend-hpa.yaml
  - frontend.yaml

labels:
  - pairs:
      project: sentinel
